services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gitgrit
      POSTGRES_PASSWORD: gitgritpassword
      POSTGRES_DB: gitgrit
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: