# Generated by Django 6.0.1 on 2026-02-27 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_stacks_policy_stack_projectstack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], default='running', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=255)),
                ('ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app.policy')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_executions', to='app.project')),
            ],
            options={
                'db_table': 'policy_executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='idx_policyexec_project_date'), models.Index(fields=['policy', '-created_at'], name='idx_policyexec_policy_date')],
            },
        ),
    ]
