# Generated by Django 6.0.1 on 2026-02-26 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tenant_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=10)),
                ('display_name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=2048)),
                ('access_token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='app.tenant')),
            ],
            options={
                'db_table': 'platform_connections',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=10)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('full_path', models.CharField(max_length=2048)),
                ('web_url', models.URLField(max_length=2048)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('webhook_id', models.CharField(blank=True, default='', max_length=255)),
                ('lifecycle', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('maintenance', 'Maintenance'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='development', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('stacks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.platformconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.tenant')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'platform_connection', 'external_id'), name='unique_tenant_connection_project')],
            },
        ),
    ]
