# Generated by Django 6.0.1 on 2026-02-27 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_platformconnection_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stacks',
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.TextField(default='def evaluate(project):\n    return {"passed": True, "score": 100, "message": "OK", "details": {}}\n')),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('draft', models.BooleanField(default=False)),
                ('ordinal', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='app.tenant')),
            ],
            options={
                'db_table': 'policies',
                'ordering': ['ordinal', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='app.tenant')),
            ],
            options={
                'db_table': 'stacks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stacks', to='app.project')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stacks', to='app.stack')),
            ],
            options={
                'db_table': 'project_stacks',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='projects', through='app.ProjectStack', to='app.stack'),
        ),
        migrations.AddConstraint(
            model_name='projectstack',
            constraint=models.UniqueConstraint(fields=('project', 'stack'), name='unique_project_stack'),
        ),
    ]
