# Generated by Django 6.0.1 on 2026-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_policyexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
