# Generated by Django 6.0.1 on 2026-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
