# Generated by Django 6.0.1 on 2026-04-05 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_policy_test_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_labels', to='app.tenant')),
            ],
            options={
                'db_table': 'policy_labels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='policies', to='app.policylabel'),
        ),
        migrations.AddConstraint(
            model_name='policylabel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_label_per_tenant'),
        ),
    ]
