# Generated by Django 6.0.1 on 2026-04-06 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_policy_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.TextField()),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('suggested_labels', models.JSONField(blank=True, default=list)),
                ('version', models.IntegerField(default=1)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketplace_policies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='source_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MarketplacePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policies', models.ManyToManyField(blank=True, related_name='packs', to='app.marketplacepolicy')),
            ],
            options={
                'db_table': 'marketplace_packs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='source_marketplace_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_policies', to='app.marketplacepolicy'),
        ),
    ]
