# Generated by Django 6.0.1 on 2026-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_policy_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
