# Generated by Django 6.0.1 on 2026-04-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_owner_to_label(apps, schema_editor):
    Project = apps.get_model("app", "Project")
    for project in Project.objects.select_related("owner").filter(owner__isnull=False):
        user = project.owner
        full_name = f"{user.first_name} {user.last_name}".strip()
        project.owner_label = full_name or user.email or str(user.pk)
        project.save(update_fields=["owner_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add the new text column alongside the existing FK
        migrations.AddField(
            model_name="project",
            name="owner_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        # 2. Copy existing FK owner names into the text column
        migrations.RunPython(copy_owner_to_label, migrations.RunPython.noop),
        # 3. Drop the FK column
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
        # 4. Rename the text column to owner
        migrations.RenameField(
            model_name="project",
            old_name="owner_label",
            new_name="owner",
        ),
    ]
