# Generated by Django 6.0.1 on 2026-04-06 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('labels_snapshot', models.JSONField(blank=True, default=list)),
                ('change_summary', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app.policy')),
            ],
            options={
                'db_table': 'policy_versions',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'version'), name='unique_policy_version')],
            },
        ),
    ]
