# Generated by Django 6.0.1 on 2026-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_owner'),
        ('app', '0011_execution_triggered_by_user'),
    ]

    operations = [
    ]
