# Generated by Django 6.0.1 on 2026-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='client_kind',
            field=models.CharField(choices=[('claude', 'Claude Code / Desktop'), ('generic', 'Generic MCP client')], default='claude', max_length=10),
        ),
    ]
