# Generated by Django 6.0.1 on 2026-05-04 13:45
# Hand-edited to add a data-migration step that encrypts pre-existing
# plaintext access tokens via the new EncryptedCharField on save.

import app.infrastructure.model_fields
from django.db import migrations

from app.infrastructure.encryption import encrypt


def encrypt_existing_tokens(apps, schema_editor):
    """Re-save every PlatformConnection so the new field encrypts the value.

    Reading a row routes through ``EncryptedCharField.from_db_value`` which is
    lenient toward legacy plaintext; saving routes through ``get_prep_value``
    which encrypts. Net effect: every row becomes ciphertext exactly once.

    Note on historical models: Django preserves custom *field* classes on
    historical models (so ``from_db_value``/``get_prep_value`` fire correctly
    here), but does NOT preserve custom model methods or manager logic. If a
    future maintainer ever moves encryption logic out of the field and into
    the model's ``save()``, this migration will silently stop encrypting.
    """
    # Fail fast: surface a missing GITGRIT_ENCRYPTION_KEY before iterating
    # rows, so we don't crash N rows in with a half-encrypted table.
    encrypt("probe")

    PlatformConnection = apps.get_model("app", "PlatformConnection")
    for conn in PlatformConnection.objects.all():
        if conn.access_token:
            conn.save(update_fields=["access_token"])


def noop(apps, schema_editor):
    # Forward-only migration: there is no safe way to recover plaintext from
    # ciphertext without the encryption key, and rolling back the schema
    # change leaves a CharField(512) which holds ciphertext fine.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_apitoken_client_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='access_token',
            field=app.infrastructure.model_fields.EncryptedCharField(max_length=1024),
        ),
        migrations.RunPython(encrypt_existing_tokens, noop),
    ]
