# Generated by Django 6.0.1 on 2026-06-05 19:28

import app.infrastructure.model_fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_feedbackreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('bedrock', 'AWS Bedrock'), ('vertex_ai', 'Google Vertex AI'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral'), ('ollama', 'Ollama'), ('litellm_proxy', 'LiteLLM Proxy')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, default='', max_length=2048)),
                ('api_key', app.infrastructure.model_fields.EncryptedCharField(max_length=1024)),
                ('available_models', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='app.tenant')),
            ],
            options={
                'db_table': 'llm_providers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('reasoning', 'Reasoning'), ('code', 'Code')], max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.llmprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_roles', to='app.tenant')),
            ],
            options={
                'db_table': 'llm_roles',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_role')],
            },
        ),
    ]
