# Generated by Django 6.0.1 on 2026-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_llmprovider_llmrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyexecution',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
