# Generated by Django 6.0.1 on 2026-06-09 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_policyexecution_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_out', to='app.stack')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_in', to='app.stack')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_dependencies', to='app.tenant')),
            ],
            options={
                'db_table': 'stack_dependencies',
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_stack_dependency'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='stack_dependency_no_self_loop')],
            },
        ),
    ]
