# Generated by Django 6.0.1 on 2026-06-09 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_stackdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_out', to='app.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_in', to='app.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_dependencies', to='app.tenant')),
            ],
            options={
                'db_table': 'project_dependencies',
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_project_dependency'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='project_dependency_no_self_loop')],
            },
        ),
    ]
