# Generated by Django 6.0.1 on 2026-06-09 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_projectdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_dependencies', to='app.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_dependencies', to='app.tenant')),
            ],
            options={
                'db_table': 'external_dependencies',
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_external_dependency')],
            },
        ),
    ]
