# Generated by Django 6.0.1 on 2026-06-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_externaldependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deps_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deps_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='deps_status',
            field=models.CharField(choices=[('none', 'Not analyzed'), ('pending', 'Queued'), ('running', 'Analyzing'), ('ok', 'Analyzed'), ('failed', 'Failed')], default='none', max_length=10),
        ),
    ]
