# Generated by Django 6.0.1 on 2026-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_project_deps_analyzed_at_project_deps_error_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externaldependency',
            name='unique_external_dependency',
        ),
        migrations.AddField(
            model_name='externaldependency',
            name='direction',
            field=models.CharField(choices=[('outbound', 'We depend on it (provider)'), ('inbound', 'It depends on us (consumer)')], default='outbound', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='externaldependency',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'direction'), name='unique_external_dependency'),
        ),
    ]
