# Generated by Django 6.0.1 on 2026-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_externaldependency_unique_external_dependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inferred_technologies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
