# Generated by Django 6.0.1 on 2026-06-10 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_project_inferred_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache'), ('queue', 'Queue / Stream'), ('storage', 'Object storage'), ('other', 'Other')], default='other', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_components', to='app.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_components', to='app.tenant')),
            ],
            options={
                'db_table': 'infrastructure_components',
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_infrastructure_component')],
            },
        ),
    ]
