# Generated by Django 6.0.1 on 2026-07-19 14:54

import app.infrastructure.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_infrastructurecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='account_login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='auth_method',
            field=models.CharField(choices=[('pat', 'Personal Access Token'), ('github_app', 'GitHub App')], default='pat', max_length=20),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformconnection',
            name='access_token',
            field=app.infrastructure.model_fields.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
    ]
