# Generated by Django 6.0.1 on 2026-08-17 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_merge_github_app_and_standard_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_standards', to='app.project')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_standards', to='app.standard')),
            ],
            options={
                'db_table': 'project_standards',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='projects', through='app.ProjectStandard', to='app.standard'),
        ),
        migrations.AddConstraint(
            model_name='projectstandard',
            constraint=models.UniqueConstraint(fields=('project', 'standard'), name='unique_project_standard'),
        ),
    ]
