# Generated by Django 6.0.1 on 2026-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_disable_draft_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deps_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
