# Generated by Django 6.0.1 on 2026-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_repoint_graph_to_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('bedrock', 'AWS Bedrock'), ('vertex_ai', 'Google Vertex AI'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral'), ('ollama', 'Ollama'), ('litellm_proxy', 'LiteLLM Proxy'), ('typesafe', 'TypeSafe (Jev)')], max_length=20),
        ),
    ]
