# Generated by Django 6.0.1 on 2026-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_repoint_graph_to_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deps_map',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='deps_source',
            field=models.CharField(blank=True, choices=[('file', '.gitgrit.yml'), ('llm', 'LLM')], default='', max_length=10),
        ),
    ]
