# Generated by Django 6.0.1 on 2026-09-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_project_deps_source_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deps_map_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
