"""
Django settings for gitgrit project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = os.environ.get("DEBUG", "False") == "True"

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-key"
    else:
        raise ValueError("SECRET_KEY environment variable is required in production")

# Fernet key for encrypting OAuth tokens at rest (see
# app.infrastructure.encryption). Production must set this; under DEBUG
# the encryption module derives a key from SECRET_KEY as a fallback.
GITGRIT_ENCRYPTION_KEY = os.environ.get("GITGRIT_ENCRYPTION_KEY")

# Build-time version stamp (set by Dockerfile via --build-arg in
# .github/workflows/publish.yml). Empty for local non-Docker runs;
# the footer template hides the version line when GIT_SHA is empty.
GIT_SHA = os.environ.get("GIT_SHA", "")
GIT_TAG = os.environ.get("GIT_TAG", "")

SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
AIRGAPPED = os.environ.get("AIRGAPPED", "False") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1"] + [
    host for host in [urlparse(SITE_URL).hostname] if host
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.gitlab",
    "allauth.socialaccount.providers.google",
    "django_htmx",
    "app",
]

MIDDLEWARE = [
    "gitgrit.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "app.middleware.TenantMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "gitgrit.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "app" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app.context_processors.tenant_context",
                "app.context_processors.version_context",
            ],
        },
    },
]

WSGI_APPLICATION = "gitgrit.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_HOST = os.environ.get("DB_HOST", "localhost")
DB_PORT = os.environ.get("DB_PORT", "5432")
DB_NAME = os.environ.get("DB_NAME", "gitgrit")
DB_USER = os.environ.get("DB_USER", "gitgrit")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "gitgritpassword")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

CSRF_TRUSTED_ORIGINS = [SITE_URL]

# kamal-proxy terminates TLS and forwards plain HTTP to the container.
# This tells Django to trust the X-Forwarded-Proto header so it knows the
# original request was HTTPS (needed for OAuth redirect URIs, CSRF, etc.).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Auth
AUTH_USER_MODEL = "app.User"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# allauth
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Per-provider auth flags. Default True so cloud deployments are unchanged;
# air-gap operators flip Google/GitHub off when no internet egress is available.
# Values must be the exact strings "True" or "False" (matches the DEBUG/AIRGAPPED
# convention above) — "true", "1", "yes" all parse as False.
AUTH_PROVIDER_GITHUB_ENABLED = os.environ.get("AUTH_PROVIDER_GITHUB_ENABLED", "True") == "True"
AUTH_PROVIDER_GITLAB_ENABLED = os.environ.get("AUTH_PROVIDER_GITLAB_ENABLED", "True") == "True"
AUTH_PROVIDER_GOOGLE_ENABLED = os.environ.get("AUTH_PROVIDER_GOOGLE_ENABLED", "True") == "True"

_ALL_SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "SCOPE": ["read:user", "user:email"],
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID", ""),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET", ""),
        },
    },
    "gitlab": {
        "SCOPE": ["read_user"],
        "APP": {
            "client_id": os.environ.get("GITLAB_CLIENT_ID", ""),
            "secret": os.environ.get("GITLAB_CLIENT_SECRET", ""),
        },
        "GITLAB_URL": os.environ.get("GITLAB_URL", "https://gitlab.com"),
    },
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"prompt": "select_account"},
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
        },
    },
}

SOCIALACCOUNT_PROVIDERS = {
    name: cfg
    for name, cfg, enabled in (
        ("github", _ALL_SOCIALACCOUNT_PROVIDERS["github"], AUTH_PROVIDER_GITHUB_ENABLED),
        ("gitlab", _ALL_SOCIALACCOUNT_PROVIDERS["gitlab"], AUTH_PROVIDER_GITLAB_ENABLED),
        ("google", _ALL_SOCIALACCOUNT_PROVIDERS["google"], AUTH_PROVIDER_GOOGLE_ENABLED),
    )
    if enabled
}

# Sandbox configuration
SANDBOX = {
    "IMAGE": "gitgrit-sandbox:latest",
    "RUNTIME": "runsc",
    "MEMORY_LIMIT": "128m",
    "CPU_LIMIT": 0.5,
    "TIMEOUT": 30,
}

TEST_RUNNER = "gitgrit.test_runner.TeardownSafeTestRunner"
